Repository sodenn/lexical-beautiful-mentions, pull requests merged in 2024-10, with the labels that each got.

#663 feat: make mention auto-spacing configurable
  .changeset/curvy-elephants-pump.md
  plugin/src/BeautifulMentionsPlugin.tsx
  plugin/src/BeautifulMentionsPluginProps.ts
  www/components/ConfigurationProvider.tsx
  www/components/Editor.tsx
  www/components/MentionsToolbarPlugin.tsx
  www/lib/useQueryParams.ts
  www/tests/menu.spec.ts-snapshots/Mention-Menu-should-dynamically-position-the-menu-1-Mobile-Safari-linux.png
  www/tests/menu.spec.ts-snapshots/Mention-Menu-should-dynamically-position-the-menu-1-chromium-linux.png
  www/tests/space.spec.ts
  www/tests/test-utils.ts
Labels: enhancement, size:M

#680 fix(): ensure space is added after multi-character trigger mention
  .changeset/sixty-jobs-perform.md
  plugin/src/BeautifulMentionsPlugin.tsx
  www/tests/space.spec.ts
Labels: bug, size:M

#689 fix(): prevent unintended deletion of text after inserting a mention
  .changeset/cold-moons-cry.md
  plugin/src/BeautifulMentionsPlugin.tsx
  www/tests/mention.spec.ts
Labels: bug, size:M

#701 chore(): update nextjs to v15
  package-lock.json
  www/app/page.tsx
  www/components/ConfigurationProvider.tsx
  www/package.json
  www/tests/menu.spec.ts-snapshots/Mention-Menu-should-dynamically-position-the-menu-1-Mobile-Safari-linux.png
  www/tests/menu.spec.ts-snapshots/Mention-Menu-should-dynamically-position-the-menu-1-chromium-linux.png
Labels: size:M

#695 feat(): insertMention function use autoSpace of config
  .changeset/stale-seals-explain.md
  plugin/src/BeautifulMentionsPlugin.tsx
  plugin/src/ComboboxPlugin.tsx
  plugin/src/mention-commands.ts
Labels: enhancement, size:M
